---
title: "R Notebook"
output:
  html_document:
    df_print: paged
editor_options: 
  chunk_output_type: console
---

Note: Run Charge_Analysis first
# Theme setup
```{r plot designs}
library(extrafont)
# font_import() # First time import of local fonts
# loadfonts(device = "win")
windowsFonts()
#### PLOT DESIGN ####
# Set color palette
pal <- c("#bb3e03","#ee9b00","yellow", "#e9d8a6","#94d2bd","#0a9396","#005f73")
pal2 <- c("light green", "#90C59B", "#F0C3E6", "#8778D7", "#1e00be", "#001219")
pal3 <- wes_palette("BottleRocket2", 21, type = "continuous")
# Set color background
bck <- "#001219"
# Set theme 
theme_custom <- theme_void()+
  theme(
    plot.margin = margin(1,1,10,1,"pt"),
    plot.background = element_rect(fill="white",color=NA),
    legend.position = "bottom",
    text = element_text(size = 12, family = "Cambria"),
    legend.title = element_text(color="black"),
    legend.text = element_text(color="black")
  )


```
# Descriptive Stats
## Charge points
```{r charge_point_ds}
# Descriptive Stats for Charge points
joined_charge_points %>% 
  mutate(X = (joined_charge_points %>% st_coordinates() %>% as_tibble())$X,
         Y = (joined_charge_points %>% st_coordinates() %>% as_tibble())$Y) %>%
  mutate(fee = factor(ifelse(is.na(`parking:fee`), "no", `parking:fee`))) %>%
  as.data.frame() %>%
  rename("Latitude" = X,
         "Longitude" = Y,
         "Capacity" = capacity,
         "Parking fee" = fee,
         # "Electic bike charging" = vehicleTypes.bike,
         # "Min power range" = powerRange.min,
         # "Max power range" = powerRange.max,
         # "Fast charger (50kwh+)" = isFastCharge
         ) %>% 
  select("Latitude", "Longitude", "Capacity", "Parking fee", -geometry) %>%
  stargazer::stargazer(type="latex", style="asr", 
                       summary = TRUE,
                       title = "PEV public charging points across Gothenburg city", 
                       notes = "Charging point data sourced from Place to Plug and Open Street Maps")

```

## Nodes

```{r nodes_ds}
# Descriptive Stats for nodes in Gothenburg road network
joined_deso.nodes %>% as.data.frame() %>% 
  select(from_node, to_node, knn_distance, dijkstras_distance) %>%
rename("From node" = from_node,
        "Charge point node" = to_node,
        "Nearest neighbour distance" = knn_distance,
        "Shortest path" = dijkstras_distance) %>%
#        "Motorbike charging" = vehicleTypes.motorbike,
#        "Electic bike charging" = vehicleTypes.bike,
#        "Min power range" = powerRange.min,
#        "Max power range" = powerRange.max,
#        "Fast charger (50kwh+)" = isFastCharge) %>%
  # tbl_summary(.,
  #           include = c(nodeID, knn_chargeId, knn_distance, distance_level),
  #           statistic = list(all_continuous() ~ "{mean} ({min}, {max})")) %>%
  #           modify_caption("**Road network nodes in Gothenburg city** (N = {N})")
stargazer::stargazer(type="latex", 
                     style="asr",
                     summary = TRUE,
                     digits=2,
                     title = "Gothenburg road network graph: Descriptive statistics", 
                     notes = "Charging point data sourced from Place to Plug and Open Street Maps")

```
# Map plots: Network
## Road network
```{r map_charge_points}
## Plot map with charge points

nodes <- got_streets_net %>% activate(nodes) %>% as_tibble() %>% st_as_sf()
ggplot() +
  #geom_sf(data = got_streets_net %>% activate(nodes) %>% as_tibble() %>% st_as_sf(), col = nodes$component, size=0.5) + 
  #geom_sf(data = gothenburg.subdiv, alpha=0.6, linewidth=0.6, colour="#8778D7", fill="#90C59B") +
  geom_sf(data = got_streets_net %>% activate(edges) %>% as_tibble() %>% st_as_sf(), linewidth=0.2, color = 'grey') +
  #geom_sf(data = main_streets$osm_lines, alpha=0.5, color = "#1e00be", linewidth=0.6) + 
  geom_sf(data = joined_charge_points, aes(size=(capacity), color=capacity)) +
  scale_color_distiller(palette = "Oranges", breaks = c(1, 25, 50, 75, 100), guide="none") +
  scale_size(breaks = c(1, 25, 50, 75, 100)) +
  labs(#title="Public PEV charging points in Gothenburg municipality",
     subtitle = "",
     color = "",
     size = "Capacity") + theme_custom
```


```{r interactive_map}
got_streets_net.unfiltered %>% activate(edges) %>% filter(from == 7790 | to==7790) %>% filter(highway== "tertiary") %>% as_tibble() %>% st_as_sf() %>% plot()

library(tmap)
tmap_mode("view") # set to interactive mode
tm_tiles("CartoDB.Positron") +
  tm_shape(st_as_sf(got_streets_net, "edges")) +
  tm_lines(col = "highway", colorNA = "red") +
  tm_shape(st_as_sf(got_streets_net.unfiltered, "nodes"))+
  tm_dots(col = st_as_sf(got_streets_net, "nodes")$id)
```

## DeSO areas
```{r map_deso_area}
## Plot map with deso areas
ggplot() +
  #geom_sf(data = water$osm_multipolygons, fill = 'light blue') + 
  geom_sf(data=gothenburg.subdiv, alpha=0.6, linewidth=0.6, colour="#8778D7", fill="#90C59B") +
  geom_sf_text(data = gothenburg.subdiv, label=gothenburg.subdiv$deso, 
               size=(scale(center=FALSE, as.integer(gothenburg.subdiv$area)) / 2), color="#1e00be") +
  # labs(title="Map of demographically statistical areas (DeSOs)",
  #    subtitle = "Gothenburg Municipality",
  #    fill = "") +
  theme_custom
```

## Nodes

```{r map_nodes}
## Plot map with node points and their color coded distance values
ggplot() +
  #geom_sf(data = streets$osm_lines, linewidth=0.2, color = '#1e00be') +
  #geom_sf(data = main_streets$osm_lines, alpha=0.8, color = "#1e00be", linewidth=0.6) + 
  #geom_sf(data = got.boundary$osm_multipolygons, linewidth=0.5, colour="grey") +
  geom_sf(data=gothenburg.subdiv, alpha=0.2, linewidth=0.6, colour="transparent", fill="#90C59B")+
  geom_sf(data = joined_deso.nodes, size=0.4, aes(color=distance_level)) +
  coord_sf(xlim = c(11.71, 12.16), 
           ylim = c(57.58, 57.86), 
           expand = TRUE, clip = "on") +
  labs(title="Nodes in Gothenburg City road network graph",
     subtitle = "By distance to charge point",
     color = "") +
  scale_color_manual(values= wes_palette(7, name = "Zissou1", type = "continuous")) +
  theme_custom + 
  theme(legend.key.width = unit(1, 'cm'))
```

## Foreign background

```{r map_deso_foreign_percentage}
foreign <- deso.demographics %>% select(deso, foreign)
got.sub.demo <- gothenburg.subdiv.merged %>% merge(., foreign, by="deso")
# Plot percentage foreign background by DeSO on heat map
ggplot() +
  #geom_sf(data=gothenburg.subdiv) +
  geom_sf(data = got.boundary$osm_multipolygons, linewidth=0.5, colour="grey") +
  geom_sf(data=got.sub.demo, alpha=0.7, aes(fill=round(foreign, 2)), linewidth=0.8) +
  #geom_sf(data = streets$osm_lines, linewidth=0.2, color = 'black') +
  coord_sf(xlim = c(11.71, 12.16), 
           ylim = c(57.57, 57.86), expand = TRUE, clip = "on") +
  labs(title="Percentage of residents with a foreign background",
       subtitle = "By DeSO subdivision",
       fill = "") +
  scale_fill_gradientn(colors = wes_palette(n=7, name = "Zissou1", type = "continuous")) +
  theme_custom
```

# Example network plots

```{r example_graph}
p1 <- st_point(c(0, 1))#
p2 <- st_point(c(2, 1))

#l2
p3 <- st_point(c(2, 2))
p4 <- st_point(c(2, 1))
p5 <- st_point(c(2, -2))
p6 <- st_point(c(2, -3))

#l3
p7 <- st_point(c(0, -2))

#l4
p8 <- st_point(c(4, -2))

l1 = st_sfc(st_linestring(c(p1, p2)))#
l2 = st_sfc(st_linestring(c(p3, p2, p4, p5, p6)))#
l3 = st_sfc(st_linestring(c(p7, p5)))#
l4 = st_sfc(st_linestring(c(p5, p8)))#
l5 = st_sfc(st_linestring(c(p7, p4)))

lines = c(l1, l2, l3, l4, l5)

edge_colors <- function(x) rep(brewer.pal(n=10, name="Set3")[-2], 2)[c(1:ecount(x))]

net <- as_sfnetwork(lines, directed=FALSE)
net <- net %>% activate(nodes) %>% mutate(nodeId = c(1:n()))
net <- net %>% activate(edges) %>% mutate(length = edge_length())
net.nodes <- net %>% activate(nodes) %>% as_tibble()

ggplot() +
  geom_sf(data = st_geometry(net, "edges"), col = edge_colors(net), lwd = 1.5) +
  geom_sf(data = st_geometry(net, "nodes"), pch = 20, size = 9, col="black") +
  geom_sf_text(data = net %>% activate(nodes) %>% as_tibble() %>% st_as_sf(), 
               label = net.nodes$nodeId, col="white") +
  theme_void()


test_path <- shortest_paths(
  graph = net,
  from = 7,
  to = 1,
  #mode = "all",
  output="both",
  algorithm ="dijkstra", # Ensure to use Dijkstra's algorithm
  weights = net %>% activate(edges) %>% pull(length)
)

test_path_graph <- net %>%
  subgraph.edges(eids = test_path$epath %>% unlist()) %>%
  as_tbl_graph()

test_path_graph_df <- test_path_graph %>% as_data_frame(., what="vertices")

#Calculate the total length of the path
test_path_graph %>%
  activate(edges) %>%
  as_tibble() %>%
  summarise(length = sum(length))

path.nodes <- test_path_graph %>% activate(nodes) %>% as_tibble()

ggplot() +
  geom_sf(data = st_geometry(net, "edges"), col = edge_colors(net), lwd = 1.5) +
  geom_sf(data = test_path_graph %>% activate(edges) %>% as_tibble( ) %>% st_as_sf(), lwd=3, col="#bb3e03") +
  geom_sf(data = st_geometry(net, "nodes"), pch = 20, size = 9, col="black") +
  geom_sf_text(data = net %>% activate(nodes) %>% as_tibble() %>% st_as_sf(), 
                label = net.nodes$nodeId, col="white") +
  geom_sf_text(data = test_path_graph %>% activate(nodes) %>% as_tibble() %>% st_as_sf(), 
                label = path.nodes$nodeId, col="white") +
  theme_void()

### Subdivided

net.simple <- as_sfnetwork(lines, directed=FALSE)
net.simple <- net.simple %>% 
  activate("edges") %>% 
  arrange(edge_length()) %>%
  filter(!edge_is_multiple()) %>%
  filter(!edge_is_loop())

net.subdivision <- convert(net.simple, to_spatial_subdivision)
net.subdivision <- net.subdivision %>% activate(edges) %>% mutate(length = edge_length())
net.subdivision <- net.subdivision %>% activate(nodes) %>% arrange(.tidygraph_node_index) %>% mutate(nodeId = c(1:n()))
net.subdivision.nodes <- net.subdivision %>% activate(nodes) %>% as_tibble()


ggplot() +
  geom_sf(data = st_geometry(net.subdivision, "edges"), col = edge_colors(net.subdivision), lwd = 1.5) +
  geom_sf(data = st_geometry(net.subdivision, "nodes"), pch = 20, size = 9, col="black") +
  geom_sf_text(data = net.subdivision %>% activate(nodes) %>% as_tibble() %>% st_as_sf(), 
               label = net.subdivision.nodes$nodeId, col="white") +
  theme_void()


test_path <- shortest_paths(
  graph = net.subdivision,
  from = 7,
  to = 1,
  #mode = "all",
  output="both",
  algorithm ="dijkstra", # Ensure to use Dijkstra's algorithm
  weights = net.subdivision %>% activate(edges) %>% pull(length)
)

test_path_graph <- net.subdivision %>%
  subgraph.edges(eids = test_path$epath %>% unlist()) %>%
  as_tbl_graph()

test_path_graph_df <- test_path_graph %>% as_data_frame(., what="vertices")

#Calculate the total length of the path
test_path_graph %>%
  activate(edges) %>%
  as_tibble() %>%
  summarise(length = sum(length))

path.nodes <- test_path_graph %>% activate(nodes) %>% as_tibble()

ggplot() +
  geom_sf(data = st_geometry(net.subdivision, "edges"), col = edge_colors(net.subdivision), lwd = 1.5) +
  geom_sf(data = test_path_graph %>% activate(edges) %>% as_tibble( ) %>% st_as_sf(), lwd=3, col="#bb3e03") +
  geom_sf(data = st_geometry(net.subdivision, "nodes"), pch = 20, size = 9, col="black") +
  geom_sf_text(data = net.subdivision %>% activate(nodes) %>% as_tibble() %>% st_as_sf(), 
               label = net.subdivision.nodes$nodeId, col="white") +
  geom_sf_text(data = test_path_graph %>% activate(nodes) %>% as_tibble() %>% st_as_sf(), 
               label = path.nodes$nodeId, col="white") +
  theme_void()

```

# Results

## Distance

### All DeSO

```{r}
normalize <- function(value, min, max) {
	normalized <- (value - min) / (max - min);
	return(normalized)
}
```

 
```{r map_deso_averages}
# Plot average distances by DeSO on cloropleth map
ggplot() +
  geom_sf(data=gothenburg.subdiv.merged, alpha=0.9, linewidth=0.4) +
  geom_sf(data=gothenburg.subdiv.merged, alpha=0.7, aes(fill=log(avg_dijk_dist)), linewidth=0.4) +
   labs(#title="Average distance to public charging point in Gothenburg",
       #subtitle = "DeSO subdivisions with min 75% rental housing",
       fill = "Average distance") +
  scale_fill_gradientn(colors = wes_palette(n=7, name = "Zissou1", type = "continuous"), 
                       #labels = c(0, 0.25, 0.5, 0.75, 1),
                       na.value="#3B9AB2") +
  theme_custom

gothenburg.subdiv.merged %>% arrange(desc(avg_dijk_dist)) %>% head(10)  %>% as_tibble() %>% count(regso)
# caption = str_wrap("Values are shown in a logorithmic scale for better representation of the variences across the DeSOs. X DeSO areas had a average accessibility of zero, which returned infinate in the logorithmic scale. These Nas are shown as the lowest color on the color scale (blue)", 100)
```

### Rentals
```{r map_rental_desos}
# Filter out desos by rental majority areas
got.sub.new.rentals <- gothenburg.subdiv.merged %>% 
  filter(deso %in% deso.demographics.rentals$deso)# %>% arrange(desc(avg_dijk_dist))
# Plot average distances by DeSO on heat map
ggplot() +
  #geom_sf(data=gothenburg.subdiv) +
  geom_sf(data=gothenburg.subdiv.merged, alpha=0.9, linewidth=0.4) +
  geom_sf(data=got.sub.new.rentals, alpha=0.7, aes(fill=(log(avg_dijk_dist))), linewidth=0.4) +
  #geom_sf(data = streets$osm_lines, linewidth=0.2, color = 'black') +
  labs(#title="Average distance to public charging point in Gothenburg",
       #subtitle = "DeSO subdivisions with min 75% rental housing",
       fill = "Average distance") +
  scale_fill_gradientn(colors = wes_palette(n=7, name = "Zissou1", type = "continuous"),
                       na.value="#3B9AB2") +
  theme_custom

got.sub.new.rentals %>% arrange(desc(avg_dijk_dist)) %>% head(10)  %>% as_tibble() %>% count(regso)
```


### Owner occupied
```{r map_owner_occupied_desos}
# Filter out desos by rental majority areas
got.sub.new.owner.occupied <- gothenburg.subdiv.merged %>% 
  filter(deso %in% deso.demographics.owner.occupied$deso)
# Plot average distances by DeSO on heat map
ggplot() +
  #geom_sf(data=gothenburg.subdiv) +
  geom_sf(data=gothenburg.subdiv.merged, alpha=0.9, linewidth=0.4) +
  geom_sf(data=got.sub.new.owner.occupied, alpha=0.7, aes(fill=log(avg_dijk_dist)), linewidth=0.4) +
  #geom_sf(data = streets$osm_lines, linewidth=0.2, color = 'black') +
  coord_sf(xlim = c(11.71, 12.16), 
           ylim = c(57.57, 57.86), expand = TRUE, clip = "on") +
  labs(title="Average distance to public charging point in Gothenburg",
       subtitle = "DeSO subdivisions with min 75% owner-occupied housing",
       fill = "Average distance",
       caption = str_wrap("Owner-occupied included all housing that is with owned outright by the resident, often a freestanding house and land (äganderätt), as well as owned apartments with a building managed by a body corporate (bostadsrätt). In both of these housing types, the residents have some or full control over facilities available to residents.", 100)) +
  scale_fill_gradientn(colors = wes_palette(n=7, name = "Zissou1", type = "continuous"),
                       na.value="#3B9AB2") +
  theme_custom
```

## Accessibility

```{r map_all_desos}
# Plot average accessibility by DeSO on map
ggplot() + 
    geom_sf(data=gothenburg.subdiv.merged, alpha=0.9, linewidth=0.4) +
  geom_sf(data = gothenburg.subdiv.merged, aes(fill=(log10(avg_accessibility))), size=0.4, linewidth=0.2) +
  labs(#title="Average accessibility to public charging point in Gothenburg",
       #subtitle = "DeSO subdivisions with min 75% rental housing",
       fill = "Average accessibility") +
  scale_fill_gradientn(colors = rev(wes_palette(n=7, name = "Zissou1", type = "continuous")), 
                       na.value="#F21A00") +
theme_custom

# Top 10
gothenburg.subdiv.merged %>% arrange((avg_accessibility)) %>% head(10)  %>% as_tibble() %>% count(regso)

```

```{r map_rental_desos}
got.sub.new.rentals %>% mutate(avg_accessibility = log(avg_accessibility))

# Plot average accessibility by DeSO on map
ggplot() + 
    geom_sf(data = gothenburg.subdiv.merged, alpha=0.9, linewidth=0.4) +
  geom_sf(data = got.sub.new.rentals, aes(fill=(log10(avg_accessibility))), size=0.4, linewidth=0.2) +
  labs(#title="Average accessibility to public charging point in Gothenburg",
       #subtitle = "DeSO subdivisions with min 75% rental housing",
       fill = "Average accessibility") +
  scale_fill_gradientn(colors = rev(wes_palette(n=7, name = "Zissou1", type = "continuous")), 
                       na.value="#F21A00") +
theme_custom

#got.sub.new.rentals %>% arrange((avg_accessibility)) %>% head(20)  %>% as_tibble() %>% select(regso, avg_accessibility)

```
 
## Descriptive Stats

```{r demographics_ds}
# Descriptive stats for full demographic data
deso.demographics %>% 
  rename(#"Nodes" = nodes, 
         #"Average distance to PEV charge point" = avg_dijk_dist,
         #"Potential accessibility" = avg_dd_accessibility,
         "Area (m^2)" = area_m2,
         "Population" = pop,
         "Total households" = total_households,
         "Swedish background" = swedish,
         "Foreign background" = foreign,
         "Higher education" = higher_education,
         "Lower education" = lower_education,
         "Rental apartment" = rental, 
         "Condominium" = condominium, 
         "Owner-occupied house" = housing,
         "Avg cars per household" = cars_per_household,
         "Total registered cars" = cars_on_road) %>%
  select(-deso, -regso, -education_missing, -avg_accessibility, -avg_dijk_dist, -avg_euc_dist) %>% 
  stargazer::stargazer(type="latex", 
                       style="asr",
                       digits=2,
                       omit.summary.stat = c("N", "Sd"), 
                       title = "DeSO demographic data for Gothenburg", 
                       notes = "Data from Statistics Sweden. Recorded 2022.")
  # tbl_summary(., include=c(-ages),
  #             statistic = list(all_continuous() ~ "{mean} ({min}, {max})")) %>%
  #             modify_footnote(all_stat_cols() ~ "Mean (Minimun) (Maximum)") %>%
  #             modify_caption("**Gothenburg city DeSO demographic data (All)** (N = {N})")
```


```{r demographics_ds}
# Sample of summarised demographic data
deso.demographics %>% arrange(desc(total_households)) %>% head() %>%
  rename(#"Nodes" = nodes, 
         #"Average distance to PEV charge point" = avg_dijk_dist,
         #"Potential accessibility" = avg_dd_accessibility,
         "Area (m^2)" = area_m2,
         "Population" = pop,
         "Total households" = total_households,
         "Swedish background" = swedish,
         "Foreign background" = foreign,
         "Higher education" = higher_education,
         "Lower education" = lower_education,
         "Rental apartment" = rental, 
         "Condominium" = condominium, 
         "Owner-occupied house" = housing,
         "Avg cars per household" = cars_per_household,
         "Total registered cars" = cars_on_road) %>%
  select(-nodes, -education_missing, -avg_accessibility, -avg_dijk_dist, -avg_euc_dist, -ages) %>% 
  stargazer::stargazer(type="latex", style="asr", digits = 2, digits.extra = 0,  flip = TRUE,  summary=FALSE, 
                       title = "DeSO demographic data for Gothenburg municipality: Sample set", notes = "DeSO demographics from 2022.")
```

```{r demographics_rentals_ds}
# Descriptive stats for rental demographic data
deso.demographics.rentals %>% 
  rename(#"Nodes" = nodes, 
         #"Average distance to PEV charge point" = avg_dijk_dist,
         #"Potential accessibility" = avg_dd_accessibility,
         "Area (m^2)" = area_m2,
         "Population" = pop,
         "Total households" = total_households,
         "Swedish background" = swedish,
         "Foreign background" = foreign,
         "Higher education" = higher_education,
         "Lower education" = lower_education,
         "Rental apartment" = rental, 
         "Condominium" = condominium, 
         "Owner-occupied house" = housing,
         "Avg cars per household" = cars_per_household,
         "Total registered cars" = cars_on_road) %>%
  select(-deso, -regso, -education_missing) %>% 
  tbl_summary(., include=c(-ages),
              statistic = list(all_continuous() ~ "{mean} ({min}, {max})")) %>%
              modify_footnote(all_stat_cols() ~ "Mean (Minimun) (Maximum)") %>%
              modify_caption("**Gothenburg DeSO demographic data
                             (areas with at least 75% rental apartment housing)** (N = {N})")
```

### Knn distance
```{r sample_knn_distance}
# Sample of summarised demographic data
closest_charge_sf  %>%
  rownames_to_column(., "from") %>% mutate(to = charge_id) %>% 
  filter(distance < 1000) %>%
  head() %>% 
  select(from, to, distance) %>%
  stargazer::stargazer(type = "latex", 
                       style = "asr",
                       summary = FALSE, 
                       rownames = FALSE,
                       digits = 0,
                       title = "Euclidean distance between points using K nearest neighbour", 
                       notes = "Note: Nearest neighbour distance is represented in meters")

```

```{r sample_dijk_distance}
# Sample of summarised demographic data Dijkstra's distance
joined_deso.nodes %>% 
  filter(dijkstras_distance < 1000) %>%
  as.data.frame() %>%
  mutate(to = chargeId, from = from_node) %>%
  mutate(dijkstras_distance = as.numeric(dijkstras_distance)) %>%
  select(from, to, dijkstras_distance) %>%
  drop_na() %>% head() %>%
  stargazer::stargazer(type="latex", 
                       style="asr",
                       summary = FALSE, 
                       rownames = FALSE,
                       digits = 0,
                       title = "Shortest distance between points using Dijkstra's algorithm", 
                       notes = "Note: Shortest distance is represented in meters")

```

## Linear regressions

```{r regression}
# Linear regressions
# stargazer(list(model1, model2, model3), type="latex", no.space = TRUE,
#           notes = "",#style="asr",
#           #report=("vc*p"),
#           dep.var.labels=c("Shortest distance (Dijkstra's)"),
#           covariate.labels=c("Foreign background", "Accessibility", "Total nodes", "Housing area", "Median income (tkr)", "Total households", "Registered cars"))

stargazer(list(model1, model2, model3), type="latex", no.space = TRUE,
          notes = "",#style="asr",
          #report=("vc*p"),
          model.numbers=FALSE,
          column.labels = c("Model 1", "Model 2", "Model 3"),
          dep.var.labels=c("Public charge point accessibility"),
          covariate.labels=c("Foreign background", "Population", "Total nodes", "Housing area", "Median income (tkr)", "Total households", "Registered cars"))

stargazer(list(model1.wt, model2.wt, model3.wt), type="latex", no.space = TRUE,
          notes = "",#style="asr",
          #report=("vc*p"),
          model.numbers=FALSE,
          column.labels = c("Model 1", "Model 2", "Model 3"),
          dep.var.labels=c("Public charge point accessibility"),
          covariate.labels=c("Foreign background", "Population", "Total nodes", "Housing area", "Median income (tkr)", "Total households", "Registered cars"))
```

```{r regression_accessibility}
# Logistic regressions
stargazer(list(model1.rentals, model2.rentals, model3.rentals), type="latex", no.space = TRUE,
          notes = "",#style="asr",
          #report=("vc*p"),
          dep.var.labels=c("Shortest distance (Dijkstra's)"),
          covariate.labels=c("Foreign background", "Accessibility", "Total nodes", "Housing area", "Median income (tkr)", "Total households", "Registered cars"))
```

## Correlation Matrix Plot

```{r correlation_plot}
# Plot correlation matrix
  ggcorrplot(corr_matrix, 
           #title = "Correlation matrix, GOT DeSO demographic data",
           method = "square",
           lab = TRUE, # Stat values
           lab_size = 2.4,
           hc.order = TRUE,
           #type = "lower",
           outline.color = "white",
           ggtheme = ggplot2::theme_minimal,
           pch = 1, 
           pch.col = "black", 
           pch.cex =1,
           tl.cex = 14) +
  theme(legend.title = element_text(family = "Cambria"),
        legend.text = element_text(family = "Cambria"),
        axis.text.x = element_text(family = "Cambria", 
                                   margin=margin(0,0,0,0),
                                   angle = 65,
                                   size = 10),
        axis.text.y = element_text(family = "Cambria", 
                                   margin=margin(0,-2,0,0),
                                   size=10)) +
  geom_vline(xintercept=1:ncol(deso.demographics)-0.5, colour="white", size=1) +
  geom_hline(yintercept=1:ncol(deso.demographics)-0.5, colour="white", size=1)
```

